# Generated by Django 5.1.4 on 2024-12-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_note_rating_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Comment',
        ),
    ]
