# Generated by Django 5.1.4 on 2024-12-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_note_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default='2024-12-21', verbose_name='Rating date'),
            preserve_default=False,
        ),
    ]
